export const TEMPLATES = [
  { id: 'mushroom',   label: 'Mushroom House',  emoji: '🍄', desc: 'Toadstool cottage with chimney',  size: '23×26×23', category: 'fantasy' },
  { id: 'ufo',        label: 'Flying Saucer',   emoji: '🛸', desc: 'Neon-rimmed UFO with pilot',      size: '25×14×25', category: 'scifi' },
  { id: 'duck',       label: 'Rubber Duck',     emoji: '🐤', desc: 'Bath duck floating in water',     size: '20×18×18', category: 'world' },
  { id: 'tv',         label: 'CRT Television',  emoji: '📺', desc: 'Wood TV with rabbit-ear antenna', size: '22×26×18', category: 'retro' },
  { id: 'crystals',   label: 'Crystal Cluster', emoji: '🔮', desc: 'Glowing shards on a rock base',   size: '21×23×19', category: 'fantasy' },
  { id: 'rocket',     label: 'Retro Rocket',    emoji: '🚀', desc: 'Finned rocket with porthole',     size: '17×31×17', category: 'scifi' },
  { id: 'snowman',    label: 'Snowman',         emoji: '⛄', desc: 'Top hat, scarf and carrot nose',  size: '19×28×18', category: 'world' },
  { id: 'cassette',   label: 'Cassette Tape',   emoji: '📼', desc: 'Mixtape with see-through reels',  size: '24×16×7',  category: 'retro' },
  { id: 'shield',     label: 'Knight Shield',   emoji: '🛡️', desc: 'Quartered heater shield in gold', size: '19×23×8',  category: 'fantasy' },
  { id: 'raygun',     label: 'Ray Gun',         emoji: '🔫', desc: 'Retro-future blaster pistol',     size: '25×17×9',  category: 'scifi' },
  { id: 'penguin',    label: 'Penguin',         emoji: '🐧', desc: 'Chubby penguin in a knit hat',    size: '18×22×16', category: 'world' },
  { id: 'camera',     label: 'Instant Camera',  emoji: '📷', desc: 'Rainbow-striped instant camera',  size: '20×17×15', category: 'retro' },
  { id: 'cactus',     label: 'Potted Cactus',   emoji: '🌵', desc: 'Ribbed cactus with a pink bloom', size: '17×24×15', category: 'world' },
  { id: 'mug',        label: 'Coffee Mug',      emoji: '☕', desc: 'Steaming mug with a heart',       size: '19×18×14', category: 'world' },
  { id: 'fox',        label: 'Woodland Fox',    emoji: '🦊', desc: 'Bright fox with a snowy tail tip', size: '21×20×18', category: 'world' },
  { id: 'whale',      label: 'Blue Whale',      emoji: '🐋', desc: 'Gentle whale with a water spout', size: '25×15×16', category: 'world' },
  { id: 'sailboat',   label: 'Sailboat',        emoji: '⛵', desc: 'Little sloop with striped sail',  size: '24×27×12', category: 'world' },
  { id: 'pumpkin',    label: 'Jack-o\'-Lantern', emoji: '🎃', desc: 'Carved pumpkin with glowing face', size: '21×19×21', category: 'world' },
  { id: 'planet',     label: 'Ringed Planet',   emoji: '🪐', desc: 'Banded gas giant with a moon',    size: '25×21×25', category: 'scifi' },
  { id: 'wizardhat',  label: 'Wizard Hat',      emoji: '🧙', desc: 'Bent starry hat with buckle',     size: '21×25×21', category: 'fantasy' },
  { id: 'joystick',   label: 'Arcade Joystick', emoji: '🕹️', desc: 'Ball-top stick with 4 buttons',   size: '18×18×16', category: 'retro' },
  { id: 'donut',      label: 'Frosted Donut',   emoji: '🍩', desc: 'Pink glaze with sprinkles',       size: '21×10×21', category: 'world' },
  { id: 'helmet',     label: 'Space Helmet',    emoji: '👨‍🚀', desc: 'Astronaut helmet with visor',   size: '21×20×21', category: 'scifi' },
  { id: 'slime',      label: 'Jelly Slime',     emoji: '🟢', desc: 'Translucent slime with a core',   size: '21×16×21', category: 'fantasy' },
  { id: 'floppy',     label: 'Floppy Disk',     emoji: '💾', desc: '3.5" disk with metal shutter',    size: '20×20×5',  category: 'retro' },
  { id: 'icecream',   label: 'Ice Cream Cone',  emoji: '🍦', desc: 'Double scoop with a cherry',      size: '17×28×17', category: 'world' },
  { id: 'drone',      label: 'Quad Drone',      emoji: '🚁', desc: 'Quadcopter with camera gimbal',   size: '25×10×25', category: 'scifi' },
  { id: 'ghost',      label: 'Friendly Ghost',  emoji: '👻', desc: 'Wavy sheet ghost saying boo',     size: '21×22×17', category: 'fantasy' },
  { id: 'lavalamp',   label: 'Lava Lamp',       emoji: '🫧', desc: 'Groovy lamp with floating blobs', size: '13×25×13', category: 'retro' },
  { id: 'frog',       label: 'Lily Pad Frog',   emoji: '🐸', desc: 'Happy frog sitting on a pad',     size: '21×15×19', category: 'world' },
  { id: 'well',       label: 'Wishing Well',    emoji: '🪣', desc: 'Stone well with a gabled roof',   size: '21×24×21', category: 'fantasy' },
  { id: 'balloon',    label: 'Hot Air Balloon', emoji: '🎈', desc: 'Striped balloon and basket',      size: '21×31×21', category: 'world' },
  { id: 'cat',        label: 'Ginger Cat',      emoji: '🐱', desc: 'Cute cozy tabby cat loaf',       size: '20×20×18', category: 'world' },
  { id: 'hovercar',   label: 'Cyber Hovercar',  emoji: '🏎️', desc: 'Futuristic neon hover flyer',    size: '24×16×18', category: 'scifi' },
  { id: 'cupcake',    label: 'Sweet Cupcake',   emoji: '🧁', desc: 'Swirled frosting with cherry',   size: '20×22×20', category: 'world' },
  { id: 'helicopter', label: 'Rescue Chopper',  emoji: '🚁', desc: 'Chopper with spinning rotor',    size: '24×20×18', category: 'world' },
  { id: 'moped',      label: 'Vintage Moped',   emoji: '🛵', desc: 'Classic retro Italian scooter',  size: '24×22×14', category: 'retro' },
  { id: 'burger',     label: 'Cheeseburger',    emoji: '🍔', desc: 'Gourmet 3D stacked burger',     size: '20×20×20', category: 'world' },
  { id: 'castle',     label: 'Medieval Castle', emoji: '🏰', desc: 'Citadel with towers & moat',     size: '24×24×24', category: 'fantasy' },
  { id: 'boombox',    label: '80s Boombox',     emoji: '📻', desc: 'Dual-speaker ghettoblaster',     size: '24×18×12', category: 'retro' },
  { id: 'chest',      label: 'Treasure Chest',  emoji: '📦', desc: 'Arched chest with brass & gems',  size: '20×20×16', category: 'fantasy' },
  { id: 'dragon',     label: 'Chibi Dragon',    emoji: '🐉', desc: 'Cute horned fire-breather',      size: '24×24×18', category: 'fantasy' },
  { id: 'spaceship',  label: 'Starfighter',     emoji: '🚀', desc: 'Sci-fi ship with ion thrusters', size: '24×24×14', category: 'scifi' },
  { id: 'robot',      label: 'Retro Mech Bot',  emoji: '🤖', desc: 'Armored robot with power core',  size: '20×24×14', category: 'scifi' },
  { id: 'campfire',   label: 'Cozy Campfire',   emoji: '🔥', desc: 'Roaring flames & marshmallow',   size: '20×20×20', category: 'world' },
  { id: 'tree',       label: 'Bonsai Island',   emoji: '🌳', desc: 'Floating island with canopy',    size: '24×24×24', category: 'world' },
  { id: 'gameboy',    label: 'Retro Handheld',  emoji: '🎮', desc: 'Classic handheld 8-bit console', size: '16×24×8',  category: 'retro' },
  { id: 'arcade',     label: 'Arcade Cabinet',  emoji: '🕹️', desc: 'Retro cabinet with CRT display',  size: '20×24×16', category: 'retro' },
  { id: 'staff',      label: 'Arcane Staff',    emoji: '🪄', desc: 'Elderwood staff with crystal',   size: '16×28×14', category: 'fantasy' },
  { id: 'wizard-tower', label: 'Wizard Tower',  emoji: '🧙', desc: 'Moonlit stone tower with stars',  size: '21×29×21', category: 'fantasy' },
  { id: 'mimic',      label: 'Chest Mimic',     emoji: '👁️', desc: 'Toothy treasure chest monster',  size: '22×18×16', category: 'fantasy' },
  { id: 'sword',      label: 'Fantasy Sword',   emoji: '⚔️', desc: 'Double-edged blade with guard',  size: '16×16×5',  category: 'fantasy' },
  { id: 'potion',     label: 'Magic Potion',    emoji: '🧪', desc: 'Glowing magical elixir flask',   size: '16×16×6',  category: 'fantasy' },
  { id: 'lighthouse', label: 'Lighthouse',      emoji: '🗼', desc: 'Coastal tower with sea beacon',  size: '20×28×18', category: 'world' },
  { id: 'moon-rover', label: 'Moon Rover',      emoji: '🛰️', desc: 'Six-wheeled lunar explorer',      size: '24×16×18', category: 'scifi' },
  { id: 'space-drone', label: 'Space Drone',    emoji: '🛸', desc: 'Four-arm survey drone',            size: '21×13×21', category: 'scifi' },
  { id: 'character',  label: 'Character',       emoji: '🧑', desc: 'Simple pixel character',         size: '8×8×4',    category: 'world' },
  { id: 'coin',       label: 'Gold Coin',       emoji: '🪙', desc: 'Shaded gold collector coin',    size: '32×32×5',  category: 'world' },
  { id: 'gem',        label: 'Crystal Gem',     emoji: '💎', desc: 'Shiny multi-faceted crystal',    size: '32×32×16', category: 'fantasy' },
  { id: 'building',   label: 'City Building',   emoji: '🏠', desc: 'Multi-story isometric tower',    size: '32×32×32', category: 'world' },
  { id: 'jukebox',    label: 'Neon Jukebox',    emoji: '🎵', desc: 'Chrome diner music machine',       size: '20×26×12', category: 'retro' },
  { id: 'typewriter', label: 'Typewriter',      emoji: '⌨️', desc: 'Classic keys with paper loaded',   size: '24×15×16', category: 'retro' },
  { id: 'satellite',  label: 'Orbital Satellite', emoji: '🛰️', desc: 'Solar craft with a glowing dish', size: '25×18×17', category: 'scifi' },
  { id: 'portal',     label: 'Energy Portal',   emoji: '🌀', desc: 'Ancient ring with a neon gateway', size: '23×23×11', category: 'scifi' },
  { id: 'mars-walker', label: 'Mars Walker',    emoji: '🤖', desc: 'Four-legged planetary scout',      size: '21×22×19', category: 'scifi' },
  { id: 'record-player', label: 'Record Player', emoji: '💿', desc: 'Turntable spinning a vinyl record', size: '24×13×20', category: 'retro' },
  { id: 'rotary-phone', label: 'Rotary Phone',  emoji: '☎️', desc: 'Colorful dial telephone',           size: '22×16×18', category: 'retro' },
  { id: 'cauldron',   label: 'Magic Cauldron',  emoji: '🫕', desc: 'Bubbling brew with ghostly smoke',  size: '21×20×21', category: 'fantasy' },
  { id: 'spellbook',  label: 'Enchanted Book',  emoji: '📖', desc: 'Open spellbook with glowing runes', size: '22×16×14', category: 'fantasy' },
  { id: 'aquarium',   label: 'Planted Aquarium', emoji: '🐠', desc: 'Glass tank with coral and fish',    size: '24×19×16', category: 'world' },
  { id: 'house',      label: 'Cozy Cottage',    emoji: '🏡', desc: 'Gabled cottage with chimney & porch', size: '24×26×24', category: 'house' },
  { id: 'door',       label: 'Front Door',      emoji: '🚪', desc: 'Wooden panel door with brass handle', size: '18×26×8',  category: 'house' },
  { id: 'window',     label: 'Cottage Window',  emoji: '🪟', desc: 'Window with flowerbox & shutters',    size: '22×22×8',  category: 'house' },
  { id: 'chair',      label: 'Dining Chair',    emoji: '🪑', desc: 'Classic wooden chair with backrest',  size: '16×24×16', category: 'house' },
  { id: 'armchair',   label: 'Cozy Armchair',   emoji: '🛋️', desc: 'Plush armchair with soft cushion',   size: '20×20×18', category: 'house' },
  { id: 'table',      label: 'Dining Table',    emoji: '🪵', desc: 'Sturdy wooden table with fruit bowl', size: '22×16×18', category: 'house' },
  { id: 'bookshelf',  label: 'Study Bookshelf', emoji: '📚', desc: 'Tall wooden shelf with colorful books', size: '20×26×10', category: 'house' },
  { id: 'pine-tree',  label: 'Evergreen Pine',  emoji: '🌲', desc: 'Tiered conifer with pinecones',       size: '20×28×20', category: 'forest' },
  { id: 'oak-tree',   label: 'Grand Oak Tree',  emoji: '🌳', desc: 'Ancient tree with roots & berries',    size: '24×28×24', category: 'forest' },
  { id: 'log-cabin',  label: 'Forest Cabin',    emoji: '🪵', desc: 'Log cabin with porch & stone chimney', size: '24×22×22', category: 'forest' },
  { id: 'stump',      label: 'Mossy Stump',     emoji: '🪵', desc: 'Weathered tree stump with mushrooms',  size: '18×16×18', category: 'forest' },
  { id: 'deer',       label: 'Forest Deer',     emoji: '🦌', desc: 'Graceful buck with majestic antlers',  size: '18×26×16', category: 'forest' },
  { id: 'mushrooms',  label: 'Wild Mushrooms',  emoji: '🍄', desc: 'Red toadstools & boletes on moss',     size: '20×18×20', category: 'forest' },
  { id: 'boulder',    label: 'Mossy Boulder',   emoji: '🪨', desc: 'Granite rock with vines & puddle',     size: '22×14×20', category: 'forest' },
]

export const CATEGORIES = [
  { id: 'all',     label: 'All' },
  { id: 'house',   label: 'House Set' },
  { id: 'forest',  label: 'Forest Set' },
  { id: 'fantasy', label: 'Fantasy' },
  { id: 'scifi',   label: 'Sci-Fi' },
  { id: 'retro',   label: 'Retro' },
  { id: 'world',   label: 'World' },
]
